#          ___ _                 _
# __  __ / __\ |__  _   _ _ __ | | __ /\  /\___  _ __  _ __   ___ _ __ ___
# \ \/ // /  | '_ \| | | | '_ \| |/ // /_/ / _ \| '_ \| '_ \ / _ \ '__/ __|
#  >  </ /___| | | | |_| | | | |   </ __  / (_) | |_) | |_) |  __/ |  \__ \
# /_/\_\____/|_| |_|\__,_|_| |_|_|\_\/ /_/ \___/| .__/| .__/ \___|_|  |___/
#                                              |_|   |_|
#         Wiki: https://xplugins.es/plugins/xchunkhoppers
#                Support: https://discord.xplugin.es
#                Donate: https://xplugins.es/donate

settings:
  enabled: true
  use-whitelist: false
  filter-list:
    - "COBBLESTONE"
    - "DIRT"
    - "ROTTEN_FLESH"

#          CONFIGURACIÓN DE MENÚS
shop-menu:
  commands:
    - "hoppershop"
    - "tiendatolvas"
    - "tolvas"
    - "tolvashoppen"
  title: "          Tienda de Tolvas"
  size: 36
  fill:
    enabled: true
    material: "BLACK_STAINED_GLASS_PANE"

  close-button:
    enabled: true
    material: "BARRIER"
    name: "&f Menú &8▸ &#FF3D3DCerrar"
    slot: 31
    lore:
      - "&8 ℹ Descripción"
      - ""
      - "&f Aqui podras cerrar  "
      - "&f este menu dando click  "
      - ""
      - "&#FF3D3D ✘ ¡Click para cerrar!"
      - ""

  price-format:
    - "&7Botón | Compra"
    - ""
    - "&7 ℹ Información:"
    - " &8 • &fPrecio: &a$%price%$ ⛃"
    - ""
    - "&e ▸ ¡Click para comprar!"
    - ""

  items:
    item_1:
      material: "HOPPER"
      type: "default"
      price: 5000.0
      slot: 10
    item_2:
      material: "HOPPER"
      type: "vip"
      price: 25000.0
      slot: 11
    item_3:
      material: "HOPPER"
      type: "god"
      price: 100000.0
      slot: 12

info-menu:
  title: "        Información de la tolva"
  size: 27
  date-format: "dd/MM/yyyy HH:mm"
  fill:
    enabled: true
    material: "GRAY_STAINED_GLASS_PANE"
  info-item:
    material: "PAPER"
    slot: 13
    name: "&#00ff00 ★ ¡Estadísticas!"
    lore:
      - "&8Información General"
      - ""
      - "&8 | &fDueño: &#FCD05C%owner%"
      - "&8 | &fTipo: &#3DFF4A%type%"
      - "&8 | &fColocado el: &#C9E4DE%date%"
      - "&8 | &fÍtems Absorbidos: &6%items%"
      - ""
      - "&#00ff00 ☄ ¡Sigue recolectando!"

  preview-slots:
    - 11
    - 12
    - 13
    - 14
    - 15

#      CONFIGURACIÓN DE TIPOS DE TOLVAS
hopper-types:
  default:
    radius: -1
    name: "&fTolva &8▸ &#00ff00&lBÁSICA &7「16x16」"
    lore:
      - "&8Objeto exclusivo"
      - ""
      - "&f Recolecta todos los ítems"
      - "&f usando esta tolva en todo"
      - "&f un chunk sin perder nada."
      - ""
      - "&#3DFF4A ▼ ¡Colócalo en el suelo! "
    hologram:
      enabled: true
      height: 1.5
      scale: 1.0
      view-distance: 20.0
      billboard: "VERTICAL"
      shadow: true
      background-color: "TRANSPARENT"
      lines:
        - "&#00ff00☄ &lTOLVA MÁGICA &#00ff00☄"
        - "&8ʀᴇᴄᴏʟᴇᴄᴛᴏʀ"
        - ""
        - "&fDueño: &#3DFF4A%player%"
        - "&fRecolectado: &6%items% items"

  vip:
    radius: 4
    name: "&fTolva &8▸ &#87CEEB&lESPECIAL &7「8x8」"
    lore:
      - "&8Objeto exclusivo"
      - ""
      - "&f Una tolva optimizada con"
      - "&f un radio de 4 bloques para"
      - "&f zonas de farmeo precisas."
      - ""
      - "&#87CEEB ▼ ¡Colócalo en el suelo! "
    hologram:
      enabled: true
      height: 1.5
      scale: 1.0
      view-distance: 20.0
      billboard: "VERTICAL"
      shadow: true
      background-color: "TRANSPARENT"
      lines:
        - "&#87CEEB☄ &lTOLVA CELESTE &#87CEEB☄"
        - "&8ʀᴇᴄᴏʟᴇᴄᴛᴏʀ ᴠɪᴘ"
        - ""
        - "&fDueño: &#87CEEB%player%"
        - "&fRecolectado: &6%items% items"

  god:
    radius: 32
    name: "&fTolva &8▸ &#CDB4DB&lDIVINA &7「64x64」"
    lore:
      - "&8Objeto exclusivo"
      - ""
      - "&f El recolector definitivo."
      - "&f Cubre un área masiva de"
      - "&f 32 bloques a la redonda."
      - ""
      - "&#CDB4DB ▼ ¡Colócalo en el suelo! "
    hologram:
      enabled: true
      height: 1.5
      scale: 1.0
      view-distance: 20.0
      billboard: "VERTICAL"
      shadow: true
      background-color: "TRANSPARENT"
      lines:
        - "&#CDB4DB☄ &lTOLVA DIVINA &#CDB4DB☄"
        - "&8ʀᴇᴄᴏʟᴇᴄᴛᴏʀ ᴍᴀsɪᴠᴏ"
        - ""
        - "&fDueño: &#CDB4DB%player%"
        - "&fRecolectado: &6%items% items"
        -
menu:
  title: "&#B3B3B3Admin hoppers menu"
  size: 27
  fill:
    enabled: true
    material: "BLACK_STAINED_GLASS_PANE"

#                MENSAJES
messages:
  prefix: "&#DBCDF0&lTOLVAS &8▸ "
  no-permission: "&c✘ No tienes permiso."
  reload: "&#00ff00✔ Configuración recargada."
  player-not-found: "&c✘ Jugador no encontrado."
  type-not-found: "&c✘ Ese tipo no existe."
  give-success: "&a✔ Has dado &e%amount%x %type% &aa &f%player%&a."
  received: "&a✔ Has recibido una &dTolva Especial&a."
  placed: "&#00ff00✔ ¡Tolva colocada!"
  broken: "&e⚠ Has retirado la tolva."
  already-exists: "&c✘ Ya hay una tolva aquí."
  shop-buy-success: "&a✔ ¡Compra exitosa! Has pagado &e$%price%&a."
  shop-insufficient-funds: "&c✘ Te faltan &e$%missing% &cpara comprar esto."
  shop-inventory-full: "&c✘ No tienes espacio en tu inventario."

version: v1.0.3